version: '3'

volumes:
  pgadmin:

services:
  scraper-api:
    restart: on-failure
    build:
      context: server
      dockerfile: ./Dockerfile
    depends_on:
      - scraper-db
    ports:
      - '3001:3001'
    command: npm run start:dev
    volumes:
      - ./server:/scraper-api/
      - /server/node_modules

  scraper-frontend:
    restart: on-failure
    build:
      context: client
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    command: npm start
    volumes:
      - ./client:/scraper-frontend/
      - /client/node_modules

  scraper-db:
    image: postgres:15.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Scraper
    restart: on-failure
    volumes:
      - ./tools/initdb.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: scraper_pgadmin
    image: dpage/pgadmin4:6.15
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
      - ./tools/servers.json:/pgadmin4/servers.json
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    restart: unless-stopped
    depends_on:
      - scraper-db
